### ISSUE TITLE
Emojis are not removed ot replaced in slug

### ISSUE THREAD

**Issue by clarkwinkelmann** [Zeokat/flarum-ext-seoslugs#2]
If you input an emoji in a discussion title, for example "Test 💯", the resulting slug will be "test-💯"

Bug or feature ?

I noticed this totally randomly because I still had your extension enabled on my test forum after the latest issue investigation.

**Comment by Zeokat** [comment]
Emojis are supported on slugs because Google support them and most of "important" Search Engines also support them.

You can do the test by yourself, simply run a query on google with the emoji 💯 and you will see the slugs with the emoji on results.
